import { Pacifico  } from "next/font/google";
import "./globals.css";


// 1. Setup the stable Inter font
const fontSans = Pacifico({
	subsets: ["latin"],
	variable: "--font-sans",
	weight:'400'
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
			<html lang="en" suppressHydrationWarning>
				<body className={` min-h-screen   antialiased ${fontSans.variable}`}>
					{children}
				</body>
			</html>
	);
}
